name: "Block PRs to main except from develop"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enforce-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "PR to main must come from develop!"
          exit 1
